GET http://localhost:3000/userlinks
###


GET http://localhost:3000/subscribers/66b266261fa47c7c3b526ccc
###

POST http://localhost:3000/userlinks
Content-Type: application/json

{
  "user": "howbaichi",
  "autolink": "ABCD",
  "address": "0xEb6fb919256C9ebc92886EfF6e289CA8E0Fdec78"
}
